API:
  NOTION_TOKEN: "your notion key"
  DATABASE_ID: "your database id" # need to connect to your connections

Topic:
  Array: "Array"
  Backtracking: "Backtracking"
  Binary Indexed Tree: "BinaryIndexedTree"
  Binary Search: "BinarySearch"
  Binary Search Tree: "BinarySearchTree"
  Binary Tree: "BinaryTree"
  Bit Manipulation: "Bit"
  Bucket Sort: "BucketSort"
  Combination: "Conbination"
  Counting: "Counting"
  Counting Sort: "CountingSort"
  Data Stream: "DataStream"
  Design: "Design"
  Depth-First Search: "DFS"
  Divide and Conquer: "Divide&Conquer"
  Dynamic Programming: "DP"
  Game Theory: "GameTheory"
  Graph: "Graph"
  Greedy: "Greedy"
  Hash Table: "HashMap"
  Heap (Priority Queue): "PriorityQueue"
  Interactive: "Interactive"
  Iterator: "Iterator"
  Linked List: "LinkedList"
  Math: "Math"
  Matrix: "Matrix"
  Memoization: "Memorization"
  Merge Sort: "MergeSort"
  Monotonic Stack: "Monotonic Stack"
  Number Theory: "NumberTheory"
  Ordered Set: "OrderedSet"
  Prefix Sum: "Prefix Sum"
  Queue: "Queue"
  Quickselect: "QuickSelect"
  Radix Sort: "RadixSort"
  Recursion: "Recursive"
  Rolling Hash: "RollingHash"
  Segment Tree: "SegmentTree"
  Simulation: "Simulation"
  Sliding Window: "SlidingWindow"
  Sorting: "Sort"
  Stack: "Stack"
  String: "String"
  String Matching: "StringMatch"
  Topological Sort: "Topological Sort"
  Tree: "Tree"
  Trie: "Trie"
  Two Pointers: "Two pointer"
  Union Find: "Union Find"
  Breadth-First Search: "BFS"

